// Cultures with multiple dialects/languages
export const cultureDialects: Record<string, { name: string; code: string }[]> = {
  chinese: [
    { name: 'Mandarin (Simplified)', code: 'zh-CN' },
    { name: 'Cantonese', code: 'zh-HK' },
    { name: 'Mandarin (Traditional/Taiwan)', code: 'zh-TW' },
  ],
  indian: [
    { name: 'Hindi', code: 'hi-IN' },
    { name: 'Tamil', code: 'ta-IN' },
    { name: 'Telugu', code: 'te-IN' },
    { name: 'Bengali', code: 'bn-IN' },
    { name: 'Gujarati', code: 'gu-IN' },
    { name: 'Marathi', code: 'mr-IN' },
    { name: 'Punjabi', code: 'pa-IN' },
    { name: 'Malayalam', code: 'ml-IN' },
    { name: 'Kannada', code: 'kn-IN' },
  ],
  filipino: [
    { name: 'Tagalog', code: 'tl-PH' },
    { name: 'Cebuano', code: 'ceb-PH' },
    { name: 'Ilocano', code: 'ilo-PH' },
  ],
  'middle eastern': [
    { name: 'Arabic', code: 'ar-SA' },
    { name: 'Farsi (Persian)', code: 'fa-IR' },
    { name: 'Hebrew', code: 'he-IL' },
    { name: 'Turkish', code: 'tr-TR' },
  ],
  spanish: [
    { name: 'Spanish (Spain)', code: 'es-ES' },
    { name: 'Spanish (Mexico)', code: 'es-MX' },
    { name: 'Spanish (Argentina)', code: 'es-AR' },
  ],
  portuguese: [
    { name: 'Portuguese (Brazil)', code: 'pt-BR' },
    { name: 'Portuguese (Portugal)', code: 'pt-PT' },
  ],
  african: [
    { name: 'Swahili', code: 'sw-KE' },
    { name: 'Amharic', code: 'am-ET' },
    { name: 'Yoruba', code: 'yo-NG' },
    { name: 'Zulu', code: 'zu-ZA' },
    { name: 'Hausa', code: 'ha-NG' },
  ],
  nigerian: [
    { name: 'Yoruba', code: 'yo-NG' },
    { name: 'Hausa', code: 'ha-NG' },
    { name: 'Igbo', code: 'ig-NG' },
  ],
  nigeria: [
    { name: 'Yoruba', code: 'yo-NG' },
    { name: 'Hausa', code: 'ha-NG' },
    { name: 'Igbo', code: 'ig-NG' },
  ],
  'sri lankan': [
    { name: 'Sinhala', code: 'si-LK' },
    { name: 'Tamil (Sri Lanka)', code: 'ta-LK' },
  ],
  'sri lanka': [
    { name: 'Sinhala', code: 'si-LK' },
    { name: 'Tamil (Sri Lanka)', code: 'ta-LK' },
  ],
};

// Default language codes for cultures without dialect options
export const defaultLanguageCodes: Record<string, string> = {
  korean: 'ko-KR',
  japanese: 'ja-JP',
  vietnamese: 'vi-VN',
  thai: 'th-TH',
  italian: 'it-IT',
  french: 'fr-FR',
  'french canadian': 'fr-CA',
  'french-canadian': 'fr-CA',
  québécois: 'fr-CA',
  quebecois: 'fr-CA',
  german: 'de-DE',
  russian: 'ru-RU',
  greek: 'el-GR',
  polish: 'pl-PL',
  dutch: 'nl-NL',
  ethiopian: 'am-ET',
  indonesian: 'id-ID',
  malaysian: 'ms-MY',
  cambodian: 'km-KH',
  burmese: 'my-MM',
  nepali: 'ne-NP',
  mongolian: 'mn-MN',
  tibetan: 'bo-CN',
  ukrainian: 'uk-UA',
  czech: 'cs-CZ',
  hungarian: 'hu-HU',
  romanian: 'ro-RO',
  swedish: 'sv-SE',
  norwegian: 'no-NO',
  danish: 'da-DK',
  finnish: 'fi-FI',
  // Spanish-speaking countries
  mexican: 'es-MX',
  mexico: 'es-MX',
  argentinian: 'es-AR',
  argentina: 'es-AR',
  colombian: 'es-CO',
  colombia: 'es-CO',
  chilean: 'es-CL',
  chile: 'es-CL',
  peruvian: 'es-PE',
  peru: 'es-PE',
  venezuelan: 'es-VE',
  venezuela: 'es-VE',
  cuban: 'es-CU',
  cuba: 'es-CU',
  'puerto rican': 'es-PR',
  'puerto rico': 'es-PR',
  dominican: 'es-DO',
  'dominican republic': 'es-DO',
  ecuadorian: 'es-EC',
  ecuador: 'es-EC',
  guatemalan: 'es-GT',
  guatemala: 'es-GT',
  honduran: 'es-HN',
  honduras: 'es-HN',
  salvadoran: 'es-SV',
  'el salvador': 'es-SV',
  nicaraguan: 'es-NI',
  nicaragua: 'es-NI',
  'costa rican': 'es-CR',
  'costa rica': 'es-CR',
  panamanian: 'es-PA',
  panama: 'es-PA',
  bolivian: 'es-BO',
  bolivia: 'es-BO',
  paraguayan: 'es-PY',
  paraguay: 'es-PY',
  uruguayan: 'es-UY',
  uruguay: 'es-UY',
  // High priority: large US immigrant communities
  haitian: 'ht-HT',
  haiti: 'ht-HT',
  pakistani: 'ur-PK',
  pakistan: 'ur-PK',
  bangladeshi: 'bn-BD',
  bangladesh: 'bn-BD',
  ghanaian: 'ak-GH',
  ghana: 'ak-GH',
  somali: 'so-SO',
  somalia: 'so-SO',
  'cape verdean': 'pt-CV',
  'cape verde': 'pt-CV',
  // Medium priority: map to existing colonial/official languages
  moroccan: 'ar-MA',
  morocco: 'ar-MA',
  algerian: 'ar-DZ',
  algeria: 'ar-DZ',
  congolese: 'fr-CD',
  'congo': 'fr-CD',
  'democratic republic of congo': 'fr-CD',
  senegalese: 'fr-SN',
  senegal: 'fr-SN',
  cameroonian: 'fr-CM',
  cameroon: 'fr-CM',
  angolan: 'pt-AO',
  angola: 'pt-AO',
};

// Display names for language codes (used to show friendly names in UI and translation prompts)
export const languageDisplayNames: Record<string, string> = {
  'ko-KR': 'Korean',
  'ja-JP': 'Japanese',
  'vi-VN': 'Vietnamese',
  'th-TH': 'Thai',
  'it-IT': 'Italian',
  'fr-FR': 'French',
  'fr-CA': 'French (Canadian)',
  'de-DE': 'German',
  'ru-RU': 'Russian',
  'el-GR': 'Greek',
  'pl-PL': 'Polish',
  'nl-NL': 'Dutch',
  'am-ET': 'Amharic',
  'id-ID': 'Indonesian',
  'ms-MY': 'Malay',
  'km-KH': 'Khmer',
  'my-MM': 'Burmese',
  'ne-NP': 'Nepali',
  'mn-MN': 'Mongolian',
  'bo-CN': 'Tibetan',
  'uk-UA': 'Ukrainian',
  'cs-CZ': 'Czech',
  'hu-HU': 'Hungarian',
  'ro-RO': 'Romanian',
  'sv-SE': 'Swedish',
  'no-NO': 'Norwegian',
  'da-DK': 'Danish',
  'fi-FI': 'Finnish',
  'es-ES': 'Spanish (Spain)',
  'es-MX': 'Spanish (Mexico)',
  'es-AR': 'Spanish (Argentina)',
  'es-CO': 'Spanish (Colombia)',
  'es-CL': 'Spanish (Chile)',
  'es-PE': 'Spanish (Peru)',
  'es-VE': 'Spanish (Venezuela)',
  'es-CU': 'Spanish (Cuba)',
  'es-PR': 'Spanish (Puerto Rico)',
  'es-DO': 'Spanish (Dominican Republic)',
  'es-EC': 'Spanish (Ecuador)',
  'es-GT': 'Spanish (Guatemala)',
  'es-HN': 'Spanish (Honduras)',
  'es-SV': 'Spanish (El Salvador)',
  'es-NI': 'Spanish (Nicaragua)',
  'es-CR': 'Spanish (Costa Rica)',
  'es-PA': 'Spanish (Panama)',
  'es-BO': 'Spanish (Bolivia)',
  'es-PY': 'Spanish (Paraguay)',
  'es-UY': 'Spanish (Uruguay)',
  'pt-BR': 'Portuguese (Brazil)',
  'pt-PT': 'Portuguese (Portugal)',
  'pt-CV': 'Portuguese (Cape Verde)',
  'pt-AO': 'Portuguese (Angola)',
  'ht-HT': 'Haitian Creole',
  'ur-PK': 'Urdu',
  'bn-BD': 'Bengali',
  'ak-GH': 'Twi (Akan)',
  'so-SO': 'Somali',
  'si-LK': 'Sinhala',
  'ta-LK': 'Tamil (Sri Lanka)',
  'yo-NG': 'Yoruba',
  'ha-NG': 'Hausa',
  'ig-NG': 'Igbo',
  'ar-MA': 'Arabic (Moroccan)',
  'ar-DZ': 'Arabic (Algerian)',
  'fr-CD': 'French (Congolese)',
  'fr-SN': 'French (Senegalese)',
  'fr-CM': 'French (Cameroonian)',
};

export function getDialectsForCulture(culture: string): { name: string; code: string }[] | null {
  const normalized = culture.toLowerCase().trim();
  return cultureDialects[normalized] || null;
}

export function getDefaultLanguageCode(culture: string): string {
  const normalized = culture.toLowerCase().trim();
  return defaultLanguageCodes[normalized] || 'en-US';
}

export function getLanguageDisplayName(code: string, fallback: string): string {
  return languageDisplayNames[code] || fallback;
}
